config_metadata: 'Saving time : Mon Apr 10 22:39:35 2023 (1681159175.2030075) ; Regime : auto-save'
experiment_logs: infer_on_train
experiment_purpose: infer_on_train
mode: infer_on_train
device: gpu
tracker_config:
  type:
  - basic
model: S1ToS2Model
lamda: 2
data_loader: baseline_dataloader
csv_path: C:\Users\Valen\OneDrive\Documents\KTH\leaf_nothing_behind\assignment-2023\image_series.csv
batch_size: 16
number_of_batches: -1
shuffle_data: true
num_workers: 4
layers_channels:
- 16
- 16
weights_path: weights/S1toS2_weights
S1toS2_weights_path: null
learning_rate: 0.001
number_of_epochs: 10
save_weights_under: ''
save_infers_under: ''
