# General config
experiment_logs:  "logs/debug"
experiment_purpose: "debugging"
mode: "train"
model: "Unet"

# Data config
data_loader: "Unet_dataloader"
batch_size: 100
num_workers: 1

# Training config
number_of_epochs: 1
save_weights_under: "weights"
number_of_batches: 1