# General config
experiment_logs: "logs/infer"
experiment_purpose: "Predicting on test data"
mode: infer
shuffle_data: false

# Data config
batch_size: 256
num_workers: 1

# Model config
weights_path: weights/unet_attention
S1toS2_weights_path: weights/S1toS2_weights